name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_image_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cloudnativeacr01.azurecr.io/Rajeshaction:latest
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: cloudnativeacr01 # ${{ secrets.ACR_NAME }}
        # Container registry password
        password: ${{ secrets.ACR_CREDENTIALS }} 
        # Container registry server url
        login-server: cloudnativeacr01.azurecr.io
        
    - name: Push the Docker image
      run: docker push cloudnativeacr01.azurecr.io/Rajeshaction:latest
      
  deploy:
    runs-on: ubuntu-latest
    needs: build_image_push # Will wait for the execution of the previous job   
    steps:
    - uses: actions/checkout@v2
    - name: Azure Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{secrets.KUBECONFIG}}  
      id: login
        
    - name: Kubernetes Deployment
      run: kubectl apply -f deployment.yaml
    - name: Service Deployment
      run: kubectl apply -f service.yaml
